//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.itim.ws.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.ibm.itim.ws.services.ArrayOfTns1WSOrganizationalContainer;


/**
 * <p>Java class for WSOrganizationalContainer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSOrganizationalContainer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://model.ws.itim.ibm.com}WSObject">
 *       &lt;sequence>
 *         &lt;element name="children" type="{http://services.ws.itim.ibm.com}ArrayOf_tns1_WSOrganizationalContainer"/>
 *         &lt;element name="parentDN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="profileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="supervisorDN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSOrganizationalContainer", propOrder = {
    "children",
    "parentDN",
    "profileName",
    "supervisorDN"
})
public class WSOrganizationalContainer
    extends WSObject
{

    @XmlElement(required = true, nillable = true)
    protected ArrayOfTns1WSOrganizationalContainer children;
    @XmlElement(required = true, nillable = true)
    protected String parentDN;
    @XmlElement(required = true, nillable = true)
    protected String profileName;
    @XmlElement(required = true, nillable = true)
    protected String supervisorDN;

    /**
     * Gets the value of the children property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTns1WSOrganizationalContainer }
     *     
     */
    public ArrayOfTns1WSOrganizationalContainer getChildren() {
        return children;
    }

    /**
     * Sets the value of the children property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTns1WSOrganizationalContainer }
     *     
     */
    public void setChildren(ArrayOfTns1WSOrganizationalContainer value) {
        this.children = value;
    }

    /**
     * Gets the value of the parentDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentDN() {
        return parentDN;
    }

    /**
     * Sets the value of the parentDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentDN(String value) {
        this.parentDN = value;
    }

    /**
     * Gets the value of the profileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * Sets the value of the profileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileName(String value) {
        this.profileName = value;
    }

    /**
     * Gets the value of the supervisorDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupervisorDN() {
        return supervisorDN;
    }

    /**
     * Sets the value of the supervisorDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupervisorDN(String value) {
        this.supervisorDN = value;
    }

}
