//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.itim.ws.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WSSession complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSSession">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clientSession" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="enforceChallengeResponse" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="locale" type="{http://model.ws.itim.ibm.com}WSLocale"/>
 *         &lt;element name="sessionID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSSession", propOrder = {
    "clientSession",
    "enforceChallengeResponse",
    "locale",
    "sessionID"
})
public class WSSession {

    @XmlElement(required = true, nillable = true)
    protected String clientSession;
    protected boolean enforceChallengeResponse;
    @XmlElement(required = true, nillable = true)
    protected WSLocale locale;
    protected long sessionID;

    /**
     * Gets the value of the clientSession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientSession() {
        return clientSession;
    }

    /**
     * Sets the value of the clientSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientSession(String value) {
        this.clientSession = value;
    }

    /**
     * Gets the value of the enforceChallengeResponse property.
     * 
     */
    public boolean isEnforceChallengeResponse() {
        return enforceChallengeResponse;
    }

    /**
     * Sets the value of the enforceChallengeResponse property.
     * 
     */
    public void setEnforceChallengeResponse(boolean value) {
        this.enforceChallengeResponse = value;
    }

    /**
     * Gets the value of the locale property.
     * 
     * @return
     *     possible object is
     *     {@link WSLocale }
     *     
     */
    public WSLocale getLocale() {
        return locale;
    }

    /**
     * Sets the value of the locale property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSLocale }
     *     
     */
    public void setLocale(WSLocale value) {
        this.locale = value;
    }

    /**
     * Gets the value of the sessionID property.
     * 
     */
    public long getSessionID() {
        return sessionID;
    }

    /**
     * Sets the value of the sessionID property.
     * 
     */
    public void setSessionID(long value) {
        this.sessionID = value;
    }

}
