//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.itim.ws.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.ibm.itim.ws.model.WSOrganizationalContainer;
import com.ibm.itim.ws.model.WSSession;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="session" type="{http://model.ws.itim.ibm.com}WSSession"/>
 *         &lt;element name="parent" type="{http://model.ws.itim.ibm.com}WSOrganizationalContainer"/>
 *         &lt;element name="newContainer" type="{http://model.ws.itim.ibm.com}WSOrganizationalContainer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "session",
    "parent",
    "newContainer"
})
@XmlRootElement(name = "createContainer")
public class CreateContainer {

    @XmlElement(required = true)
    protected WSSession session;
    @XmlElement(required = true)
    protected WSOrganizationalContainer parent;
    @XmlElement(required = true)
    protected WSOrganizationalContainer newContainer;

    /**
     * Gets the value of the session property.
     * 
     * @return
     *     possible object is
     *     {@link WSSession }
     *     
     */
    public WSSession getSession() {
        return session;
    }

    /**
     * Sets the value of the session property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSSession }
     *     
     */
    public void setSession(WSSession value) {
        this.session = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link WSOrganizationalContainer }
     *     
     */
    public WSOrganizationalContainer getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSOrganizationalContainer }
     *     
     */
    public void setParent(WSOrganizationalContainer value) {
        this.parent = value;
    }

    /**
     * Gets the value of the newContainer property.
     * 
     * @return
     *     possible object is
     *     {@link WSOrganizationalContainer }
     *     
     */
    public WSOrganizationalContainer getNewContainer() {
        return newContainer;
    }

    /**
     * Sets the value of the newContainer property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSOrganizationalContainer }
     *     
     */
    public void setNewContainer(WSOrganizationalContainer value) {
        this.newContainer = value;
    }

}
