//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.itim.ws.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.ibm.itim.ws.model.WSLocale;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="principle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wsLocale" type="{http://model.ws.itim.ibm.com}WSLocale"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "principle",
    "wsLocale"
})
@XmlRootElement(name = "getChallengeQuestions")
public class GetChallengeQuestions {

    @XmlElement(required = true)
    protected String principle;
    @XmlElement(required = true)
    protected WSLocale wsLocale;

    /**
     * Gets the value of the principle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrinciple() {
        return principle;
    }

    /**
     * Sets the value of the principle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrinciple(String value) {
        this.principle = value;
    }

    /**
     * Gets the value of the wsLocale property.
     * 
     * @return
     *     possible object is
     *     {@link WSLocale }
     *     
     */
    public WSLocale getWsLocale() {
        return wsLocale;
    }

    /**
     * Sets the value of the wsLocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSLocale }
     *     
     */
    public void setWsLocale(WSLocale value) {
        this.wsLocale = value;
    }

}
