//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.itim.ws.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getItimFixpackLevelReturn" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getItimFixpackLevelReturn"
})
@XmlRootElement(name = "getItimFixpackLevelResponse")
public class GetItimFixpackLevelResponse {

    protected int getItimFixpackLevelReturn;

    /**
     * Gets the value of the getItimFixpackLevelReturn property.
     * 
     */
    public int getGetItimFixpackLevelReturn() {
        return getItimFixpackLevelReturn;
    }

    /**
     * Sets the value of the getItimFixpackLevelReturn property.
     * 
     */
    public void setGetItimFixpackLevelReturn(int value) {
        this.getItimFixpackLevelReturn = value;
    }

}
