//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.itim.ws.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getItimVersionReturn" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getItimVersionReturn"
})
@XmlRootElement(name = "getItimVersionResponse")
public class GetItimVersionResponse {

    protected float getItimVersionReturn;

    /**
     * Gets the value of the getItimVersionReturn property.
     * 
     */
    public float getGetItimVersionReturn() {
        return getItimVersionReturn;
    }

    /**
     * Sets the value of the getItimVersionReturn property.
     * 
     */
    public void setGetItimVersionReturn(float value) {
        this.getItimVersionReturn = value;
    }

}
