//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.itim.ws.services;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.ibm.itim.ws.exceptions.WSApplicationException;
import com.ibm.itim.ws.exceptions.WSInvalidSessionException;
import com.ibm.itim.ws.exceptions.WSLoginServiceException;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.itim.ws.services package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Fault1_QNAME = new QName("http://services.ws.itim.ibm.com", "fault1");
    private final static QName _Fault2_QNAME = new QName("http://services.ws.itim.ibm.com", "fault2");
    private final static QName _Fault_QNAME = new QName("http://services.ws.itim.ibm.com", "fault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.itim.ws.services
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateAccountResponse }
     * 
     */
    public UpdateAccountResponse createUpdateAccountResponse() {
        return new UpdateAccountResponse();
    }

    /**
     * Create an instance of {@link GetDefaultAccountAttributesByPerson }
     * 
     */
    public GetDefaultAccountAttributesByPerson createGetDefaultAccountAttributesByPerson() {
        return new GetDefaultAccountAttributesByPerson();
    }

    /**
     * Create an instance of {@link OrphanAccounts }
     * 
     */
    public OrphanAccounts createOrphanAccounts() {
        return new OrphanAccounts();
    }

    /**
     * Create an instance of {@link SearchAccountsResponse }
     * 
     */
    public SearchAccountsResponse createSearchAccountsResponse() {
        return new SearchAccountsResponse();
    }

    /**
     * Create an instance of {@link GetAccountAttributesResponse }
     * 
     */
    public GetAccountAttributesResponse createGetAccountAttributesResponse() {
        return new GetAccountAttributesResponse();
    }

    /**
     * Create an instance of {@link SuspendAccount }
     * 
     */
    public SuspendAccount createSuspendAccount() {
        return new SuspendAccount();
    }

    /**
     * Create an instance of {@link CreateAccount }
     * 
     */
    public CreateAccount createCreateAccount() {
        return new CreateAccount();
    }

    /**
     * Create an instance of {@link ModifyAccount }
     * 
     */
    public ModifyAccount createModifyAccount() {
        return new ModifyAccount();
    }

    /**
     * Create an instance of {@link AdoptSingleAccountResponse }
     * 
     */
    public AdoptSingleAccountResponse createAdoptSingleAccountResponse() {
        return new AdoptSingleAccountResponse();
    }

    /**
     * Create an instance of {@link AdoptAccountsResponse }
     * 
     */
    public AdoptAccountsResponse createAdoptAccountsResponse() {
        return new AdoptAccountsResponse();
    }

    /**
     * Create an instance of {@link DeprovisionAccount }
     * 
     */
    public DeprovisionAccount createDeprovisionAccount() {
        return new DeprovisionAccount();
    }

    /**
     * Create an instance of {@link GetDefaultAccountAttributes }
     * 
     */
    public GetDefaultAccountAttributes createGetDefaultAccountAttributes() {
        return new GetDefaultAccountAttributes();
    }

    /**
     * Create an instance of {@link OrphanSingleAccount }
     * 
     */
    public OrphanSingleAccount createOrphanSingleAccount() {
        return new OrphanSingleAccount();
    }

    /**
     * Create an instance of {@link GetAccountProfileForServiceResponse }
     * 
     */
    public GetAccountProfileForServiceResponse createGetAccountProfileForServiceResponse() {
        return new GetAccountProfileForServiceResponse();
    }

    /**
     * Create an instance of {@link RestoreAccountResponse }
     * 
     */
    public RestoreAccountResponse createRestoreAccountResponse() {
        return new RestoreAccountResponse();
    }

    /**
     * Create an instance of {@link UpdateAccount }
     * 
     */
    public UpdateAccount createUpdateAccount() {
        return new UpdateAccount();
    }

    /**
     * Create an instance of {@link GetDefaultAccountAttributesByPersonResponse }
     * 
     */
    public GetDefaultAccountAttributesByPersonResponse createGetDefaultAccountAttributesByPersonResponse() {
        return new GetDefaultAccountAttributesByPersonResponse();
    }

    /**
     * Create an instance of {@link SearchAccounts }
     * 
     */
    public SearchAccounts createSearchAccounts() {
        return new SearchAccounts();
    }

    /**
     * Create an instance of {@link GetAccountAttributes }
     * 
     */
    public GetAccountAttributes createGetAccountAttributes() {
        return new GetAccountAttributes();
    }

    /**
     * Create an instance of {@link OrphanAccountsResponse }
     * 
     */
    public OrphanAccountsResponse createOrphanAccountsResponse() {
        return new OrphanAccountsResponse();
    }

    /**
     * Create an instance of {@link SuspendAccountResponse }
     * 
     */
    public SuspendAccountResponse createSuspendAccountResponse() {
        return new SuspendAccountResponse();
    }

    /**
     * Create an instance of {@link CreateAccountResponse }
     * 
     */
    public CreateAccountResponse createCreateAccountResponse() {
        return new CreateAccountResponse();
    }

    /**
     * Create an instance of {@link ModifyAccountResponse }
     * 
     */
    public ModifyAccountResponse createModifyAccountResponse() {
        return new ModifyAccountResponse();
    }

    /**
     * Create an instance of {@link AdoptSingleAccount }
     * 
     */
    public AdoptSingleAccount createAdoptSingleAccount() {
        return new AdoptSingleAccount();
    }

    /**
     * Create an instance of {@link AdoptAccounts }
     * 
     */
    public AdoptAccounts createAdoptAccounts() {
        return new AdoptAccounts();
    }

    /**
     * Create an instance of {@link DeprovisionAccountResponse }
     * 
     */
    public DeprovisionAccountResponse createDeprovisionAccountResponse() {
        return new DeprovisionAccountResponse();
    }

    /**
     * Create an instance of {@link GetDefaultAccountAttributesResponse }
     * 
     */
    public GetDefaultAccountAttributesResponse createGetDefaultAccountAttributesResponse() {
        return new GetDefaultAccountAttributesResponse();
    }

    /**
     * Create an instance of {@link GetAccountProfileForService }
     * 
     */
    public GetAccountProfileForService createGetAccountProfileForService() {
        return new GetAccountProfileForService();
    }

    /**
     * Create an instance of {@link OrphanSingleAccountResponse }
     * 
     */
    public OrphanSingleAccountResponse createOrphanSingleAccountResponse() {
        return new OrphanSingleAccountResponse();
    }

    /**
     * Create an instance of {@link RestoreAccount }
     * 
     */
    public RestoreAccount createRestoreAccount() {
        return new RestoreAccount();
    }

    /**
     * Create an instance of {@link ArrayOfXsdString }
     * 
     */
    public ArrayOfXsdString createArrayOfXsdString() {
        return new ArrayOfXsdString();
    }

    /**
     * Create an instance of {@link ArrayOfTns1WSAttribute }
     * 
     */
    public ArrayOfTns1WSAttribute createArrayOfTns1WSAttribute() {
        return new ArrayOfTns1WSAttribute();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSApplicationException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ws.itim.ibm.com", name = "fault1")
    public JAXBElement<WSApplicationException> createFault1(WSApplicationException value) {
        return new JAXBElement<WSApplicationException>(_Fault1_QNAME, WSApplicationException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSInvalidSessionException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ws.itim.ibm.com", name = "fault2")
    public JAXBElement<WSInvalidSessionException> createFault2(WSInvalidSessionException value) {
        return new JAXBElement<WSInvalidSessionException>(_Fault2_QNAME, WSInvalidSessionException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSLoginServiceException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ws.itim.ibm.com", name = "fault")
    public JAXBElement<WSLoginServiceException> createFault(WSLoginServiceException value) {
        return new JAXBElement<WSLoginServiceException>(_Fault_QNAME, WSLoginServiceException.class, null, value);
    }

}
