//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.itim.ws.services;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.ibm.itim.ws.model.WSAccount;
import com.ibm.itim.ws.model.WSSession;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="session" type="{http://model.ws.itim.ibm.com}WSSession"/>
 *         &lt;element name="systemUserDN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wsAccounts" type="{http://model.ws.itim.ibm.com}WSAccount" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "session",
    "systemUserDN",
    "wsAccounts"
})
@XmlRootElement(name = "orphanAccounts")
public class OrphanAccounts {

    @XmlElement(required = true)
    protected WSSession session;
    @XmlElement(required = true)
    protected String systemUserDN;
    @XmlElement(required = true)
    protected List<WSAccount> wsAccounts;

    /**
     * Gets the value of the session property.
     * 
     * @return
     *     possible object is
     *     {@link WSSession }
     *     
     */
    public WSSession getSession() {
        return session;
    }

    /**
     * Sets the value of the session property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSSession }
     *     
     */
    public void setSession(WSSession value) {
        this.session = value;
    }

    /**
     * Gets the value of the systemUserDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemUserDN() {
        return systemUserDN;
    }

    /**
     * Sets the value of the systemUserDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemUserDN(String value) {
        this.systemUserDN = value;
    }

    /**
     * Gets the value of the wsAccounts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wsAccounts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWsAccounts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WSAccount }
     * 
     * 
     */
    public List<WSAccount> getWsAccounts() {
        if (wsAccounts == null) {
            wsAccounts = new ArrayList<WSAccount>();
        }
        return this.wsAccounts;
    }

}
