//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.itim.ws.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.ibm.itim.ws.model.WSSearchArguments;
import com.ibm.itim.ws.model.WSSession;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="session" type="{http://model.ws.itim.ibm.com}WSSession"/>
 *         &lt;element name="searchArgs" type="{http://model.ws.itim.ibm.com}WSSearchArguments"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "session",
    "searchArgs"
})
@XmlRootElement(name = "searchAccounts")
public class SearchAccounts {

    @XmlElement(required = true)
    protected WSSession session;
    @XmlElement(required = true)
    protected WSSearchArguments searchArgs;

    /**
     * Gets the value of the session property.
     * 
     * @return
     *     possible object is
     *     {@link WSSession }
     *     
     */
    public WSSession getSession() {
        return session;
    }

    /**
     * Sets the value of the session property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSSession }
     *     
     */
    public void setSession(WSSession value) {
        this.session = value;
    }

    /**
     * Gets the value of the searchArgs property.
     * 
     * @return
     *     possible object is
     *     {@link WSSearchArguments }
     *     
     */
    public WSSearchArguments getSearchArgs() {
        return searchArgs;
    }

    /**
     * Sets the value of the searchArgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSSearchArguments }
     *     
     */
    public void setSearchArgs(WSSearchArguments value) {
        this.searchArgs = value;
    }

}
