//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.itim.ws.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.ibm.itim.ws.model.WSOrganizationalContainer;
import com.ibm.itim.ws.model.WSSession;

@WebService(name = "WSOrganizationalContainerService", targetNamespace = "http://services.ws.itim.ibm.com")
@XmlSeeAlso({
    com.ibm.itim.ws.exceptions.ObjectFactory.class,
    com.ibm.itim.ws.model.ObjectFactory.class,
    com.ibm.itim.ws.services.ObjectFactory.class
})
public interface WSOrganizationalContainerService {


    /**
     * 
     * @param session
     * @return
     *     returns java.util.List<com.ibm.itim.ws.model.WSOrganizationalContainer>
     * @throws WSApplicationException
     * @throws WSLoginServiceException
     */
    @WebMethod
    @WebResult(name = "getOrganizationsReturn", targetNamespace = "http://services.ws.itim.ibm.com")
    @RequestWrapper(localName = "getOrganizations", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.GetOrganizations")
    @ResponseWrapper(localName = "getOrganizationsResponse", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.GetOrganizationsResponse")
    public List<WSOrganizationalContainer> getOrganizations(
        @WebParam(name = "session", targetNamespace = "http://services.ws.itim.ibm.com")
        WSSession session)
        throws WSApplicationException, WSLoginServiceException
    ;

    /**
     * 
     * @param session
     * @param parent
     * @return
     *     returns com.ibm.itim.ws.model.WSOrganizationalContainer
     * @throws WSApplicationException
     * @throws WSLoginServiceException
     */
    @WebMethod
    @WebResult(name = "getOrganizationSubTreeReturn", targetNamespace = "http://services.ws.itim.ibm.com")
    @RequestWrapper(localName = "getOrganizationSubTree", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.GetOrganizationSubTree")
    @ResponseWrapper(localName = "getOrganizationSubTreeResponse", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.GetOrganizationSubTreeResponse")
    public WSOrganizationalContainer getOrganizationSubTree(
        @WebParam(name = "session", targetNamespace = "http://services.ws.itim.ibm.com")
        WSSession session,
        @WebParam(name = "parent", targetNamespace = "http://services.ws.itim.ibm.com")
        WSOrganizationalContainer parent)
        throws WSApplicationException, WSLoginServiceException
    ;

    /**
     * 
     * @param session
     * @return
     *     returns java.util.List<com.ibm.itim.ws.model.WSOrganizationalContainer>
     * @throws WSApplicationException
     * @throws WSLoginServiceException
     */
    @WebMethod
    @WebResult(name = "getOrganizationTreeReturn", targetNamespace = "http://services.ws.itim.ibm.com")
    @RequestWrapper(localName = "getOrganizationTree", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.GetOrganizationTree")
    @ResponseWrapper(localName = "getOrganizationTreeResponse", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.GetOrganizationTreeResponse")
    public List<WSOrganizationalContainer> getOrganizationTree(
        @WebParam(name = "session", targetNamespace = "http://services.ws.itim.ibm.com")
        WSSession session)
        throws WSApplicationException, WSLoginServiceException
    ;

    /**
     * 
     * @param attributeValue
     * @param session
     * @param attributeName
     * @param parent
     * @return
     *     returns java.util.List<com.ibm.itim.ws.model.WSOrganizationalContainer>
     * @throws WSApplicationException
     * @throws WSLoginServiceException
     */
    @WebMethod
    @WebResult(name = "searchContainerByAttributeReturn", targetNamespace = "http://services.ws.itim.ibm.com")
    @RequestWrapper(localName = "searchContainerByAttribute", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.SearchContainerByAttribute")
    @ResponseWrapper(localName = "searchContainerByAttributeResponse", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.SearchContainerByAttributeResponse")
    public List<WSOrganizationalContainer> searchContainerByAttribute(
        @WebParam(name = "session", targetNamespace = "http://services.ws.itim.ibm.com")
        WSSession session,
        @WebParam(name = "parent", targetNamespace = "http://services.ws.itim.ibm.com")
        WSOrganizationalContainer parent,
        @WebParam(name = "attributeName", targetNamespace = "http://services.ws.itim.ibm.com")
        String attributeName,
        @WebParam(name = "attributeValue", targetNamespace = "http://services.ws.itim.ibm.com")
        String attributeValue)
        throws WSApplicationException, WSLoginServiceException
    ;

    /**
     * 
     * @param attributeValue
     * @param wsparent
     * @param session
     * @param attributeName
     * @return
     *     returns java.util.List<com.ibm.itim.ws.model.WSOrganizationalContainer>
     * @throws WSApplicationException
     */
    @WebMethod
    @WebResult(name = "searchContainerTreeByAttributeReturn", targetNamespace = "http://services.ws.itim.ibm.com")
    @RequestWrapper(localName = "searchContainerTreeByAttribute", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.SearchContainerTreeByAttribute")
    @ResponseWrapper(localName = "searchContainerTreeByAttributeResponse", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.SearchContainerTreeByAttributeResponse")
    public List<WSOrganizationalContainer> searchContainerTreeByAttribute(
        @WebParam(name = "session", targetNamespace = "http://services.ws.itim.ibm.com")
        WSSession session,
        @WebParam(name = "wsparent", targetNamespace = "http://services.ws.itim.ibm.com")
        WSOrganizationalContainer wsparent,
        @WebParam(name = "attributeName", targetNamespace = "http://services.ws.itim.ibm.com")
        String attributeName,
        @WebParam(name = "attributeValue", targetNamespace = "http://services.ws.itim.ibm.com")
        String attributeValue)
        throws WSApplicationException
    ;

    /**
     * 
     * @param profileName
     * @param session
     * @param parent
     * @param containerName
     * @return
     *     returns java.util.List<com.ibm.itim.ws.model.WSOrganizationalContainer>
     * @throws WSApplicationException
     * @throws WSLoginServiceException
     */
    @WebMethod
    @WebResult(name = "searchContainerByNameReturn", targetNamespace = "http://services.ws.itim.ibm.com")
    @RequestWrapper(localName = "searchContainerByName", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.SearchContainerByName")
    @ResponseWrapper(localName = "searchContainerByNameResponse", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.SearchContainerByNameResponse")
    public List<WSOrganizationalContainer> searchContainerByName(
        @WebParam(name = "session", targetNamespace = "http://services.ws.itim.ibm.com")
        WSSession session,
        @WebParam(name = "parent", targetNamespace = "http://services.ws.itim.ibm.com")
        WSOrganizationalContainer parent,
        @WebParam(name = "profileName", targetNamespace = "http://services.ws.itim.ibm.com")
        String profileName,
        @WebParam(name = "containerName", targetNamespace = "http://services.ws.itim.ibm.com")
        String containerName)
        throws WSApplicationException, WSLoginServiceException
    ;

    /**
     * 
     * @param newContainer
     * @param session
     * @param parent
     * @return
     *     returns com.ibm.itim.ws.model.WSOrganizationalContainer
     * @throws WSApplicationException
     * @throws WSLoginServiceException
     */
    @WebMethod
    @WebResult(name = "createContainerReturn", targetNamespace = "http://services.ws.itim.ibm.com")
    @RequestWrapper(localName = "createContainer", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.CreateContainer")
    @ResponseWrapper(localName = "createContainerResponse", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.CreateContainerResponse")
    public WSOrganizationalContainer createContainer(
        @WebParam(name = "session", targetNamespace = "http://services.ws.itim.ibm.com")
        WSSession session,
        @WebParam(name = "parent", targetNamespace = "http://services.ws.itim.ibm.com")
        WSOrganizationalContainer parent,
        @WebParam(name = "newContainer", targetNamespace = "http://services.ws.itim.ibm.com")
        WSOrganizationalContainer newContainer)
        throws WSApplicationException, WSLoginServiceException
    ;

    /**
     * 
     * @param session
     * @param wsOrgContainer
     * @throws WSApplicationException
     * @throws WSLoginServiceException
     */
    @WebMethod
    @RequestWrapper(localName = "modifyContainer", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.ModifyContainer")
    @ResponseWrapper(localName = "modifyContainerResponse", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.ModifyContainerResponse")
    public void modifyContainer(
        @WebParam(name = "session", targetNamespace = "http://services.ws.itim.ibm.com")
        WSSession session,
        @WebParam(name = "wsOrgContainer", targetNamespace = "http://services.ws.itim.ibm.com")
        WSOrganizationalContainer wsOrgContainer)
        throws WSApplicationException, WSLoginServiceException
    ;

    /**
     * 
     * @param session
     * @param orgContainerDN
     * @throws WSApplicationException
     * @throws WSLoginServiceException
     */
    @WebMethod
    @RequestWrapper(localName = "removeContainer", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.RemoveContainer")
    @ResponseWrapper(localName = "removeContainerResponse", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.RemoveContainerResponse")
    public void removeContainer(
        @WebParam(name = "session", targetNamespace = "http://services.ws.itim.ibm.com")
        WSSession session,
        @WebParam(name = "orgContainerDN", targetNamespace = "http://services.ws.itim.ibm.com")
        String orgContainerDN)
        throws WSApplicationException, WSLoginServiceException
    ;

    /**
     * 
     * @param session
     * @param orgContainerDN
     * @return
     *     returns com.ibm.itim.ws.model.WSOrganizationalContainer
     * @throws WSApplicationException
     * @throws WSLoginServiceException
     */
    @WebMethod
    @WebResult(name = "lookupContainerReturn", targetNamespace = "http://services.ws.itim.ibm.com")
    @RequestWrapper(localName = "lookupContainer", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.LookupContainer")
    @ResponseWrapper(localName = "lookupContainerResponse", targetNamespace = "http://services.ws.itim.ibm.com", className = "com.ibm.itim.ws.services.LookupContainerResponse")
    public WSOrganizationalContainer lookupContainer(
        @WebParam(name = "session", targetNamespace = "http://services.ws.itim.ibm.com")
        WSSession session,
        @WebParam(name = "orgContainerDN", targetNamespace = "http://services.ws.itim.ibm.com")
        String orgContainerDN)
        throws WSApplicationException, WSLoginServiceException
    ;

}
