//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.itim.ws.services;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "WSOrganizationalContainerServiceService", targetNamespace = "http://services.ws.itim.ibm.com", wsdlLocation = "WEB-INF/wsdl/WSOrganizationalContainerService.wsdl")
public class WSOrganizationalContainerServiceService
    extends Service
{

    private final static URL WSORGANIZATIONALCONTAINERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException WSORGANIZATIONALCONTAINERSERVICESERVICE_EXCEPTION;
    private final static QName WSORGANIZATIONALCONTAINERSERVICESERVICE_QNAME = new QName("http://services.ws.itim.ibm.com", "WSOrganizationalContainerServiceService");

    static {
            WSORGANIZATIONALCONTAINERSERVICESERVICE_WSDL_LOCATION = com.ibm.itim.ws.services.WSOrganizationalContainerServiceService.class.getResource("/WEB-INF/wsdl/WSOrganizationalContainerService.wsdl");
        WebServiceException e = null;
        if (WSORGANIZATIONALCONTAINERSERVICESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/WSOrganizationalContainerService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        WSORGANIZATIONALCONTAINERSERVICESERVICE_EXCEPTION = e;
    }

    public WSOrganizationalContainerServiceService() {
        super(__getWsdlLocation(), WSORGANIZATIONALCONTAINERSERVICESERVICE_QNAME);
    }

    public WSOrganizationalContainerServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSORGANIZATIONALCONTAINERSERVICESERVICE_QNAME);
    }

    public WSOrganizationalContainerServiceService(URL wsdlLocation) {
        super(wsdlLocation, WSORGANIZATIONALCONTAINERSERVICESERVICE_QNAME);
    }

    public WSOrganizationalContainerServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSORGANIZATIONALCONTAINERSERVICESERVICE_QNAME);
    }

    public WSOrganizationalContainerServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSOrganizationalContainerServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns WSOrganizationalContainerService
     */
    @WebEndpoint(name = "WSOrganizationalContainerService")
    public WSOrganizationalContainerService getWSOrganizationalContainerService() {
        return super.getPort(new QName("http://services.ws.itim.ibm.com", "WSOrganizationalContainerService"), WSOrganizationalContainerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSOrganizationalContainerService
     */
    @WebEndpoint(name = "WSOrganizationalContainerService")
    public WSOrganizationalContainerService getWSOrganizationalContainerService(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.ws.itim.ibm.com", "WSOrganizationalContainerService"), WSOrganizationalContainerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSORGANIZATIONALCONTAINERSERVICESERVICE_EXCEPTION!= null) {
            throw WSORGANIZATIONALCONTAINERSERVICESERVICE_EXCEPTION;
        }
        return WSORGANIZATIONALCONTAINERSERVICESERVICE_WSDL_LOCATION;
    }

}
