//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.itim.ws.services;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "WSPersonServiceService", targetNamespace = "http://services.ws.itim.ibm.com", wsdlLocation = "WEB-INF/wsdl/WSPersonService.wsdl")
public class WSPersonServiceService
    extends Service
{

    private final static URL WSPERSONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException WSPERSONSERVICESERVICE_EXCEPTION;
    private final static QName WSPERSONSERVICESERVICE_QNAME = new QName("http://services.ws.itim.ibm.com", "WSPersonServiceService");

    static {
            WSPERSONSERVICESERVICE_WSDL_LOCATION = com.ibm.itim.ws.services.WSPersonServiceService.class.getResource("/WEB-INF/wsdl/WSPersonService.wsdl");
        WebServiceException e = null;
        if (WSPERSONSERVICESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/WSPersonService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        WSPERSONSERVICESERVICE_EXCEPTION = e;
    }

    public WSPersonServiceService() {
        super(__getWsdlLocation(), WSPERSONSERVICESERVICE_QNAME);
    }

    public WSPersonServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSPERSONSERVICESERVICE_QNAME);
    }

    public WSPersonServiceService(URL wsdlLocation) {
        super(wsdlLocation, WSPERSONSERVICESERVICE_QNAME);
    }

    public WSPersonServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSPERSONSERVICESERVICE_QNAME);
    }

    public WSPersonServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSPersonServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns WSPersonService
     */
    @WebEndpoint(name = "WSPersonService")
    public WSPersonService getWSPersonService() {
        return super.getPort(new QName("http://services.ws.itim.ibm.com", "WSPersonService"), WSPersonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSPersonService
     */
    @WebEndpoint(name = "WSPersonService")
    public WSPersonService getWSPersonService(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.ws.itim.ibm.com", "WSPersonService"), WSPersonService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSPERSONSERVICESERVICE_EXCEPTION!= null) {
            throw WSPERSONSERVICESERVICE_EXCEPTION;
        }
        return WSPERSONSERVICESERVICE_WSDL_LOCATION;
    }

}
