//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.itim.ws.services;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "WSSessionService", targetNamespace = "http://services.ws.itim.ibm.com", wsdlLocation = "WEB-INF/wsdl/WSSessionService.wsdl")
public class WSSessionService_Service
    extends Service
{

    private final static URL WSSESSIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSSESSIONSERVICE_EXCEPTION;
    private final static QName WSSESSIONSERVICE_QNAME = new QName("http://services.ws.itim.ibm.com", "WSSessionService");

    static {
            WSSESSIONSERVICE_WSDL_LOCATION = com.ibm.itim.ws.services.WSSessionService_Service.class.getResource("/WEB-INF/wsdl/WSSessionService.wsdl");
        WebServiceException e = null;
        if (WSSESSIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/WSSessionService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        WSSESSIONSERVICE_EXCEPTION = e;
    }

    public WSSessionService_Service() {
        super(__getWsdlLocation(), WSSESSIONSERVICE_QNAME);
    }

    public WSSessionService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSESSIONSERVICE_QNAME);
    }

    public WSSessionService_Service(URL wsdlLocation) {
        super(wsdlLocation, WSSESSIONSERVICE_QNAME);
    }

    public WSSessionService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSESSIONSERVICE_QNAME);
    }

    public WSSessionService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSSessionService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns WSSessionService
     */
    @WebEndpoint(name = "WSSessionServicePort")
    public WSSessionService getWSSessionServicePort() {
        return super.getPort(new QName("http://services.ws.itim.ibm.com", "WSSessionServicePort"), WSSessionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSSessionService
     */
    @WebEndpoint(name = "WSSessionServicePort")
    public WSSessionService getWSSessionServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.ws.itim.ibm.com", "WSSessionServicePort"), WSSessionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSESSIONSERVICE_EXCEPTION!= null) {
            throw WSSESSIONSERVICE_EXCEPTION;
        }
        return WSSESSIONSERVICE_WSDL_LOCATION;
    }

}
